#!/bin/sh
# Generate the Homebrew formula for a released version from its checksums.txt.
# Usage: scripts/gen-formula.sh <version-without-v>  > Formula/arco.rb
#
# Reads checksums.txt from the GitHub release and emits a multi-platform formula
# (macOS + Linux, amd64 + arm64). Used by the release workflow and runnable by
# hand to refresh the tap.
set -eu

ver="${1:?usage: gen-formula.sh <version e.g. 0.1.0> [checksums-file]}"
repo="dinhlongviolin1/arco"
base="https://github.com/$repo/releases/download/v$ver"

# Checksums come from a local file if given (2nd arg) — lets the caller retry
# the download to dodge release-propagation races — otherwise fetched directly.
if [ "${2:-}" != "" ] && [ -f "$2" ]; then
  sums=$(cat "$2")
else
  sums=$(curl -fsSL "$base/checksums.txt")
fi
sha() { echo "$sums" | grep " arco_$1\$" | cut -d' ' -f1; }

d_arm=$(sha darwin_arm64.tar.gz)
d_amd=$(sha darwin_amd64.tar.gz)
l_arm=$(sha linux_arm64.tar.gz)
l_amd=$(sha linux_amd64.tar.gz)

for v in "$d_arm" "$d_amd" "$l_arm" "$l_amd"; do
  [ -n "$v" ] || { echo "missing a checksum for v$ver in checksums.txt" >&2; exit 1; }
done

cat <<EOF
# typed: false
# frozen_string_literal: true

# Homebrew formula for arco — fleet supervisor for coding agents.
# Works on macOS and Linux (Linuxbrew). Regenerated by scripts/gen-formula.sh
# on each release; do not edit by hand.
class Arco < Formula
  desc "Command your worker agents the way a bow commands the strings"
  homepage "https://github.com/$repo"
  version "$ver"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "$base/arco_darwin_arm64.tar.gz"
      sha256 "$d_arm"
    end
    on_intel do
      url "$base/arco_darwin_amd64.tar.gz"
      sha256 "$d_amd"
    end
  end

  on_linux do
    on_arm do
      url "$base/arco_linux_arm64.tar.gz"
      sha256 "$l_arm"
    end
    on_intel do
      url "$base/arco_linux_amd64.tar.gz"
      sha256 "$l_amd"
    end
  end

  def install
    bin.install "arco"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/arco version")
  end
end
EOF
